### ISSUE TITLE
Request Features Legend and Overrides on Apache EChart

### ISSUE THREAD

**Issue by itsnull12** [VolkovLabs/business-charts#217]
Hi VolkovLabs Team,

Is it possbile Apache Echart can combine the default Legend and Overrides from the official Grafana panel ?

![Screenshot from 2023-10-16 10-36-47](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/81866625/9b93ed97-8ef2-4252-8643-ea077b471780)

Notes:
Left side from Offical Panel
Right side from Apache Echart Plugin

I need information like Mean and Total at the bottom of the Grafana official panel. I need configure the option Legend and Overrides

![Screenshot from 2023-10-16 10-37-59](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/81866625/59b35c1c-ce4b-4e42-a3f7-494524c28852)

![Screenshot from 2023-10-16 10-39-05](https://github.com/VolkovLabs/volkovlabs-echarts-panel/assets/81866625/6e2cde01-073c-4a12-8d41-93fcab92be15)

Thank you ^^

**Comment by mikhail-vl** [comment]
@itsnull12 Thank you for opening feature request.

  We will look into adding it in the future version.

**Comment by mikhail-vl** [comment]
I have not seen additional requests for Legend and Overrides since the issue was opened.
  Closing for now until we see more requests.
