### ISSUE TITLE
Type Bar in Visual Editor

### ISSUE THREAD

**Issue by Luca13062004** [VolkovLabs/business-charts#314]
Hi Everyone,

I am working with grafana for about a month and recently found out about the business charts plug in. 
For my grafana Dashboard I insert the following data out of my influx DB

<img width="683" alt="data table" src="https://github.com/user-attachments/assets/a3bbb153-5938-4036-808a-5f541d7bdeea">

Now in the function field I took the following code:

return {
  dataset: context.editor.dataset,
  series: context.editor.series,
  xAxis: {
    type: 'time',
  },
  yAxis: {
    type: 'value',
    min: 'dataMin',
  },
}

As I am then using the Visual Editor to display my data everything looks fine as far as I am using the type line for my graph. But when I am switching the type to Bar then I can not select the data used for x and y axis. The Visualization nonetheless shows bars but they are not displaying the values of the column selected but it seems as if the bars are displaying the value of the first column of my table ("cumulative planned test execution"). 

<img width="651" alt="data graph" src="https://github.com/user-attachments/assets/2da9b7cb-431a-486b-9780-c0903fd18a5a">
<img width="632" alt="Visual Editor type line" src="https://github.com/user-attachments/assets/7979db5f-a6bc-4cb7-b1fc-cbc0f9223e95">
<img width="620" alt="Visual Editor type bar" src="https://github.com/user-attachments/assets/ea3fd27d-5692-430a-81e2-5e33b08f4cec">
<img width="600" alt="Graph with type Bar" src="https://github.com/user-attachments/assets/db6b4cc0-eea4-45a9-82c3-96a76845021f">

Is that an error or do I need to add some code in the function section? Furthermore how do I secure that my whole value from the date column is displayed on the x-axis? At the moment there is just for example 15 instead of 2024-07-15. Thank you very much in advance.

**Comment by mikhail-vl** [comment]
Resolves in #322
