### ISSUE TITLE
Histogram from bar visualization ?

### ISSUE THREAD

**Issue by lukasmrtvy** [VolkovLabs/business-charts#318]
Hi,
I have data in Prometheus format:
```
requests_latency_bucket{le="0.003"} 81902
requests_latency_bucket{le="0.006"} 500
requests_latency_bucket{le="0.009"} 15000
```
, but I am not sure, how ( if even possible ) to create a histogram similar to the:
<img width="1083" alt="image" src="https://github.com/user-attachments/assets/8114b98f-7f8a-468a-9c42-c5a2cd2417af">

The closest I can get is this bar chart, but it shows accumulation, instead of distribution per bucket:
<img width="929" alt="image" src="https://github.com/user-attachments/assets/9d57b5e8-45c6-4ba2-8e4a-e22e2caf528e">

Thanks

**Comment by vitPinchuk** [comment]
@lukasmrtvy Thank you for your question.

To transform data here is [Grafana Doc.](https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#histogram), please, you can based on it. 

And, to create a histogram by Apache Echarts, please, check this great example from [Apache Echarts](https://echarts.apache.org/examples/en/editor.html?c=bar-histogram)

Example based on `ecStat:histogram`. In code editor, you have access to `context.ecStat`, `context.ecStat.histogram` 

Please, watch the video with examples. The video explains how to work with histograms , [volkovlabs - ecstat](https://volkovlabs.io/plugins/business-charts/tutorials/ecstat/)
