### ISSUE TITLE
Clickable column to drill down dashboard 

### ISSUE THREAD

**Issue by maxbaiw29** [VolkovLabs/business-charts#323]
Dear Madam/Sir, 
I am  using your business charts plugin, which I find very good. I was wondering if you could help me on creating a clickable column, to drill down to another dashboard. I tried the data links but it is not exactly what I m looking. Please see the code I am using:   

...... series : [
{
   emphasis: {
        focus: 'series'
      },
      link: {
        target: 'blank',
        formatter: function(params) {
          let encodedName = encodeURIComponent(params.name);
          return `URL with variable`;
        }
      }
}
]

**Comment by vitPinchuk** [comment]
@maxbaiw29 Thank you for your question. 

To use chart events (click, mouse events, legendselectchanged etc.), please use `.on` method. Here is the Apache documentation part [documentation](https://echarts.apache.org/en/api.html#events)

`context.panel.chart` gives you access to the Instance of the Apache ECharts library. Here is [documentation for panel](https://volkovlabs.io/plugins/business-charts/options/#parameters)

Here is an example with code to solve your issue for bar type:

![image](https://github.com/user-attachments/assets/4eaaa6fd-b5d5-44bd-bc8a-ca509d9cbb57)


code to copy: 
```js
/**
 * Register click using chart instance 
 */
context.panel.chart.on('click', (params) => {
  if (params.seriesName === 'S1') {
    /**
     * Go to dashboard
     */
    context.grafana.locationService.replace('/d/E9NLNnFVz/bar?orgId=1');
  } else if (params.seriesName === 'S2') {
    /**
     * Go to dashboard
     */
    context.grafana.locationService.replace('/d/E9NLNnFVz/bar?orgId=1');
  }
});

return {
  tooltip: {},
  legend: {
    data: ["S1", "S2"],
  },
  xAxis: {
    data: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
  },
  yAxis: {},
  series: [
    {
      name: "S1",
      type: "bar",
      data: [120, 132, 101, 134, 90, 230, 210],
    },
    {
      name: "S2",
      type: "bar",
      data: [220, 182, 191, 234, 290, 330, 310],
    },
  ],
}


``` 


Here is another example with code to solve your issue for line type:

![image](https://github.com/user-attachments/assets/42338eef-60c1-4ac1-97fd-4a840d052320)

code to copy: 
```js
/**
 * Register click using chart instance 
 */
context.panel.chart.on('click', (params) => {
  if (params.seriesName === 'S1') {
    /**
     * Go to dashboard
     */
    context.grafana.locationService.replace('/d/E9NLNnFVz/bar?orgId=1');
  } else if (params.seriesName === 'S2') {
    /**
     * Go to dashboard
     */
    context.grafana.locationService.replace('/d/E9NLNnFVz/bar?orgId=1');
  }
});

return {
  tooltip: {},
  legend: {
    data: ["S1", "S2"],
  },
  xAxis: {
    data: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
  },
  yAxis: {},
  series: [
    {
      name: "S1",
      type: "line",
      data: [120, 132, 101, 134, 90, 230, 210],
    },
    {
      name: "S2",
      type: "line",
      data: [220, 182, 191, 234, 290, 330, 310],
    },
  ],
}


```
