### ISSUE TITLE
Update event documentation to reflect v6 breaking changes

### ISSUE THREAD

**Issue by sebyon** [VolkovLabs/business-charts#326]
Hey team, 

Not sure if below is correct, but might have noticed that documentation following breaking changes from v6 is not up to date. 

Following from below that helped me find my issue:

> @lesh3000 Business Charts v6 introduced breaking changes. All parameters are available using `context` only.
> 
> Please look at the documentation for the updated parameters: https://volkovlabs.io/plugins/volkovlabs-echarts-panel/options/#parameters.

_Originally posted by @mikhail-vl in https://github.com/VolkovLabs/business-charts/issues/305#issuecomment-2212615608_

## Example: Event Handling 
In the [Event Handling](https://volkovlabs.io/plugins/business-charts/events/) documentation for [update of time range](https://volkovlabs.io/plugins/business-charts/events/#update-of-time-range), the example image and code have the following

```javascript
/**
 * Update Time Range on Zoom
 */
context.panel.chart.on("datazoom", function (params) {
  const startValue = params.batch[0]?.startValue;
  const endValue = params.batch[0]?.endValue;
  locationService.partial({ from: startValue, to: endValue });
});
```

where after breaking changes should (well only way i got it working) be:

```javascript
/**
 * Update Time Range on Zoom
 */
context.panel.chart.on("datazoom", function (params) {
  const startValue = params.batch[0]?.startValue;
  const endValue = params.batch[0]?.endValue;
  context.grafana.locationService.partial({ from: startValue, to: endValue });
});
```

Also looks like the default code when utilising the business chart visualisation still references the previous one. 

Again, unsure if I'm just doing something wrong, but otherwise would be nice to update for newcomers like me.

**Comment by vitPinchuk** [comment]
@sebyon Thank you. 

We will update the not actual parts in the documentation

**Comment by mikhail-vl** [comment]
@sebyon Thank you for the feedback.

Documentation updated: https://volkovlabs.io/plugins/business-charts/events/
