### ISSUE TITLE
Scatter Type in visual editor

### ISSUE THREAD

**Issue by CptOrange16** [VolkovLabs/business-charts#328]
Hello

I am building a plot with multiple series. 
At the moment, all the series are lines but I would like for some of them to be points instead of the full line.

![imagem](https://github.com/user-attachments/assets/c70d53b7-372e-4fd7-8e2b-dc8b4be63d9a)

If we choose the type Line we can configure the name and the x and y variables but in the scatter type i don't see these configurations.

**Comment by mikhail-vl** [comment]
Resolved in https://github.com/VolkovLabs/business-charts/pull/332
