### ISSUE TITLE
geoJSON sluggish and unresponsive

### ISSUE THREAD

**Issue by supportdesk-si** [VolkovLabs/business-charts#344]
Latest version of the plugin. Using default USA or custom geoJSON the panel becomes non-responsive. No matter the setup, it responses well right after load, zooming and moving it the first time works. After that panel gets stuck.

**Comment by supportdesk-si** [comment]
This is not related to plugin. eCharts boundingCoords option is the issue. Opening ticket there.

**Comment by mikhail-vl** [comment]
@supportdesk-si Thank you for letting us know.

  We follow latest ECharts versions and will update when released.
