### ISSUE TITLE
Can't seem to get the correct column name when using time series format

### ISSUE THREAD

**Issue by Bragor95** [VolkovLabs/business-charts#347]
Hey there,

I am a huge fan of your products and especially your Business Chart integration saved me countless times. Thanks so much! :)

However, I do have a small issue right now. My data comes from a TimescaleDB and I am using Version 6.0.0 of your plugin.

I have a query that basically looks like that:
`SELECT interval as time,
  (last_value - LAG(last_value) OVER (PARTITION BY id ORDER BY interval)) AS value_difference,
  meter_name
FROM 
  interval_data
ORDER BY 
  interval, meter_name;

and I have Grafana set to use Time Series as my data format. As you can see in Grafana the title of the column consists of 'value_difference' and then besides the meter_name. If I use Grafanas visualisation options this combination of values can be seen in the tooltip and also in the legend.
![Screenshot 2024-10-23 at 17 55 09](https://github.com/user-attachments/assets/3f7fee68-9cfd-44a4-be52-4a400484de8b)
<img width="1789" alt="Screenshot 2024-10-23 at 18 03 29" src="https://github.com/user-attachments/assets/49063a7d-d77a-4bd5-8af3-6495a3cc8b88">

However, when I try to access the title in business charts by using .name on one of the fields I simply get back 'value_difference' for every field which makes it impossible to create a meaningful legend.
![Screenshot 2024-10-23 at 17 59 29](https://github.com/user-attachments/assets/1f94b93e-fc01-46f1-8c05-d653cdbf1b41)

Do you know a way to somehow transform the data in Grafana or simply use the correct call in echarts?

**Comment by vitPinchuk** [comment]
@Bragor95 Thank you for your question. 

Here is simple example like yours. 
![image](https://github.com/user-attachments/assets/a2183be9-4e99-4712-afa3-f981cb6ee06d)

I use the visual editor 
![image](https://github.com/user-attachments/assets/a0772857-7868-4169-87e5-659abd999214)  

code example: 
```js 
console.log('console >>> context',context)
return {
  dataset: context.editor.dataset,
  series: context.editor.series,
  legend: {
    data: ['Line', 'Line2']
  },
  grid: {
    bottom: "3%",
    containLabel: true,
    left: "3%",
    right: "4%",
    top: "4%"
  },
  xAxis: {
    type: "category"
  },
  yAxis: {
    type: 'value',
  },
}
```

To set legend in visual editor, please add legend property to chart settings. Note, that names in data should be the same in  
 `context.editor.series` for each series, another words the same with name in editor for series
 
 I keep `console.log('console >>> context',context)` as an example, please you can use it with developer mode in the browser to check all parameters available in context for code editor
 
 You can use 
 `console.log('console >>> context', context.panel.data.series[0].fields)`

To check fields with names from the data. It can help you to use appropriate field names 
![image](https://github.com/user-attachments/assets/7d1eff14-05a6-452a-a3a5-32c226b7ca32)

Please use it fields for `legend->data`, but it should be the same with appropriate series `name` property 
[apache](https://echarts.apache.org/en/option.html#series-line.name)

Let me know if you find it helpful

**Comment by Bragor95** [comment]
Thank you very much! This was very helpful :)
