### ISSUE TITLE
ECharts VolkovLabs Plugin Geo Maps: "Cannot read properties of undefined (reading 'regions')" Error on Map Initialization

### ISSUE THREAD

**Issue by beyzacevik** [VolkovLabs/business-charts#350]
I am using Geo Maps on Grafana to visualize data. With the below settings:

Renderer: SVG 
Maps:  JSON

After no changes to the code or environment, the map visualization using the VolkovLabs ECharts plugin fails with the error.

> TypeError: Cannot read properties of undefined (reading 'regions').

This issue occurs when setting up a map visualization with GeoJSON data. The same code and plugin version worked correctly yesterday, but the error is now consistently reproducible. This behavior is unexpected, given that no updates or configuration changes have been made.

 It does not work with the most simplified version code as below.
```

function loadItalyMap() {
  $.get(
    "path/to/italy_provinces.json",
    (geoJsonItaly) => {
      const options = {
        tooltip: {
          trigger: "item",
          formatter: "{b}", // Display province name
        },
        series: [
          {
            type: "map",
            map: "italy",
            label: {
              show: true, // Show province names
            },
            itemStyle: {
              emphasis: { areaColor: "#b0c4de" },
            },
            data: geoJsonItaly.features.map((feature) => ({
              name: feature.properties.prov_name,
              value: 1, // Dummy value
            })),
          },
        ],
      };

      context.panel.chart.setOption(options);
    }
  ).fail((_, textStatus, errorThrown) => {
    console.error("Error loading Italy GeoJSON:", textStatus, errorThrown);
  });
}

loadItalyMap();
```

**Environment**
Grafana Version:  v11.3.0-pre (unknown-de)
VolkovLabs ECharts Plugin Version: 6.4.1

Can you please inform me why this could happen?

**Comment by beyzacevik** [comment]
I updated the map with below constant: 

'map: "italy"' to 'map: "Italy"' and I seems to be working. 

Could you please provide detailed information on why this could possibly happen?

**Comment by vitPinchuk** [comment]
@beyzacevik thanks for the open question

In this case, this is the context of working directly with the Apache Eharts library.
Most likely, this is due to how the country name is stored in the JSON
